#!/usr/bin/env python3
"""Non-default conditional-CE diagnostic for the raw OGBench CEM runner.

The checked-in paper path remains unchanged. This diagnostic replays the
actual versioned store and router, then labels occupied groups with

    D(G | M, q) = [L(M without G, q) - L(M, q)] / [L(empty, q) + eps].

Deleting a group rebuilds the store without its payload, so same-key fallback,
capacity, promotion, and routing are recomputed rather than copied from the
full-store decision. Pair deletions supervise redundancy/complementarity.
"""
from __future__ import annotations

import argparse
import ast
from dataclasses import asdict, dataclass
import hashlib
import json
import math
from pathlib import Path
import random
import sys
import time
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lewm.models.cem_controller import VersionedEventStore  # noqa: E402
from scripts.run_cem_raw_ogbench import (  # noqa: E402
    ActionConditionedHost,
    QuerySample,
    QueryTensors,
    RawMemoryConditioner,
    StoreConfig,
    assign_semantic_keys,
    batches,
    build_queries,
    compute_group_ce_targets,
    discover_events,
    env_family,
    horizon_loss,
    one_step_surprise,
    ordered_query_events,
    rank_correlation,
    rollout,
    set_seed,
    source_contract_audit,
    stable_json,
    tensor_digest,
    tensorize_queries,
    train_ce_calibrator,
    train_host,
    train_memory,
    tune_store_config,
)

DEFAULT_OUTPUT = ROOT / "outputs/graph_cem_conditional_v1"
DEFAULT_BASE_OUTPUT = ROOT / "outputs/cem_raw_ogbench"
FOCUSED_ENVS = (
    "pointmaze-large-navigate-v0",
    "cube-single-play-v0",
    "puzzle-3x3-play-v0",
)
FORBIDDEN_NAMES = {
    "cue_labels",
    "cue_positions",
    "cue_window",
    "reward",
    "goal_state",
}


def json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, np.ndarray):
        return json_safe(value.tolist())
    if isinstance(value, (np.floating, float)):
        number = float(value)
        return number if math.isfinite(number) else None
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.bool_):
        return bool(value)
    return value


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def resolve_device(gpu: int) -> torch.device:
    if gpu == 3:
        raise ValueError("GPU3 is prohibited for this campaign")
    if gpu not in (0, 1, 2):
        raise ValueError(f"GPU must be one of 0,1,2; received {gpu}")
    if not torch.cuda.is_available():
        return torch.device("cpu")
    torch.cuda.set_device(gpu)
    return torch.device(f"cuda:{gpu}")


def conditional_source_audit() -> dict[str, Any]:
    tree = ast.parse(Path(__file__).read_text())
    loaded_names = {
        node.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)
    }
    violations = sorted(FORBIDDEN_NAMES & loaded_names)
    return {
        "passed": not violations and source_contract_audit()["passed"],
        "forbidden_loaded_names": violations,
        "input_artifact": (
            "train-only PCA DINO features generated by the raw runner from "
            "cache arrays frames/actions only"
        ),
        "training_labels": (
            "frozen-host future loss under actual-store singleton and pair "
            "deletions; no cue/event class or time labels"
        ),
        "test_future_used_for_training": False,
        "paper_default_path_modified": False,
    }


def feature_path(base_output: Path, env_name: str) -> Path:
    return base_output / "features" / env_name / "features.npz"


def base_checkpoint_path(
    base_output: Path,
    env_name: str,
    seed: int,
) -> Path:
    return base_output / "cells" / env_name / f"s{seed}" / "model.pt"


def cell_dir(output: Path, env_name: str, seed: int) -> Path:
    return output / "cells" / env_name / f"s{seed}"


def diagnostic_config(base: StoreConfig, max_events: int) -> StoreConfig:
    """Increase only diagnostic occupancy/read budget, not learned thresholds."""
    budget = min(int(max_events), max(4, int(base.budget)))
    return StoreConfig(
        promotion_threshold=float(base.promotion_threshold),
        hysteresis=float(base.hysteresis),
        budget=budget,
        topk=min(2, budget),
        verification_delay=int(base.verification_delay),
    )


@dataclass
class ReplayScores:
    ce_hat: torch.Tensor
    route: torch.Tensor
    combined: torch.Tensor


@torch.no_grad()
def store_scores(
    memory: RawMemoryConditioner,
    batch: QueryTensors,
) -> ReplayScores:
    ce_hat = memory.query_ce_hat(
        batch.context_z,
        batch.future_actions[:, 0],
        batch.events,
        batch.metadata,
    )
    route = memory.scores(
        batch.context_z,
        batch.future_actions[:, 0],
        batch.events,
        batch.metadata,
    )
    route_mean = (
        route.masked_fill(~batch.valid, 0.0).sum(1, keepdim=True)
        / batch.valid.sum(1, keepdim=True).clamp_min(1)
    )
    return ReplayScores(
        ce_hat=ce_hat,
        route=route,
        combined=ce_hat + 0.01 * (route - route_mean),
    )


@torch.no_grad()
def replay_store_masks(
    batch: QueryTensors,
    queries: list[QuerySample],
    config: StoreConfig,
    scores: ReplayScores,
    excluded: torch.Tensor | None = None,
) -> tuple[torch.Tensor, torch.Tensor, dict[str, Any]]:
    """Rebuild the version store and reroute after dependency-closed deletion."""
    if excluded is None:
        excluded = torch.zeros_like(batch.valid)
    if excluded.shape != batch.valid.shape:
        raise ValueError("excluded mask shape does not match query store")
    selected = torch.zeros_like(batch.valid)
    occupied = torch.zeros_like(batch.valid)
    fallback_after_deletion = 0
    selected_deleted_payloads = 0
    occupancies = []
    for row, query in enumerate(queries):
        events = ordered_query_events(query, batch.events.shape[1])
        store = VersionedEventStore(
            budget=int(config.budget),
            hysteresis=float(config.hysteresis),
        )
        excluded_keys = {
            events[column].key_id
            for column in range(len(events))
            if bool(excluded[row, column])
        }
        for column, event in enumerate(events):
            if bool(excluded[row, column]):
                continue
            store.propose(
                event_id=event.event_id,
                key_id=event.key_id,
                event_timestamp=event.peak_t,
                proposed_at=event.start,
            )
            verified_at = event.end + int(config.verification_delay)
            if verified_at > query.query_t:
                continue
            store.verify(
                event_id=event.event_id,
                verified_at=verified_at,
                ce_hat=float(scores.ce_hat[row, column]),
                threshold=float(config.promotion_threshold),
            )
        active_ids = {record.event_id for record in store.active()}
        active_columns = [
            column
            for column, event in enumerate(events)
            if event.event_id in active_ids
        ]
        if excluded_keys:
            fallback_after_deletion += sum(
                events[column].key_id in excluded_keys
                for column in active_columns
            )
        if active_columns:
            occupied[row, active_columns] = True
            ranking = sorted(
                active_columns,
                key=lambda column: float(scores.combined[row, column]),
                reverse=True,
            )
            recalled = ranking[: min(int(config.topk), len(ranking))]
            selected[row, recalled] = True
        occupancies.append(len(active_columns))
        selected_deleted_payloads += int(bool((selected[row] & excluded[row]).any()))
    occupancy = np.asarray(occupancies, dtype=np.float64)
    telemetry = {
        "mean_occupancy": float(occupancy.mean()) if len(occupancy) else 0.0,
        "maximum_occupancy": int(occupancy.max(initial=0)),
        "multi_group_query_count": int((occupied.sum(1) >= 2).sum()),
        "fallback_versions_after_deletion": int(fallback_after_deletion),
        "selected_deleted_payloads": int(selected_deleted_payloads),
        "dependency_payload_leaks": int(selected_deleted_payloads),
        "router_rerun_after_deletion": True,
    }
    return selected, occupied, telemetry


def normalized_conditional_effect(
    deleted_loss: torch.Tensor,
    full_loss: torch.Tensor,
    empty_loss: torch.Tensor,
) -> torch.Tensor:
    return (deleted_loss - full_loss) / empty_loss.clamp_min(1e-8)


@dataclass
class ConditionalTargets:
    singleton: torch.Tensor
    pair: torch.Tensor
    candidate: torch.Tensor
    pair_valid: torch.Tensor
    full_mask: torch.Tensor
    full_loss: torch.Tensor
    empty_loss: torch.Tensor
    telemetry: dict[str, Any]


@torch.no_grad()
def per_query_loss(
    host: ActionConditionedHost,
    memory: RawMemoryConditioner | None,
    batch: QueryTensors,
    mask: torch.Tensor | None = None,
    batch_size: int = 512,
) -> torch.Tensor:
    values = []
    for start in range(0, len(batch), batch_size):
        stop = min(len(batch), start + batch_size)
        index = torch.arange(start, stop, device=batch.context_z.device)
        part = batch.index(index)
        part_mask = None if mask is None else mask[start:stop]
        prediction, _ = rollout(host, memory, part, mask=part_mask)
        values.append(horizon_loss(prediction, part.targets).mean(1))
    return torch.cat(values)


@torch.no_grad()
def compute_conditional_targets(
    host: ActionConditionedHost,
    memory: RawMemoryConditioner,
    batch: QueryTensors,
    queries: list[QuerySample],
    config: StoreConfig,
    batch_size: int,
) -> ConditionalTargets:
    scores = store_scores(memory, batch)
    full_mask, occupied, full_telemetry = replay_store_masks(
        batch, queries, config, scores
    )
    full_loss = per_query_loss(
        host, memory, batch, full_mask, batch_size=batch_size
    )
    empty_loss = per_query_loss(
        host, None, batch, None, batch_size=batch_size
    )
    rows, slots = batch.valid.shape
    singleton = torch.zeros((rows, slots), device=batch.valid.device)
    pair = torch.zeros((rows, slots, slots), device=batch.valid.device)
    fallback_count = 0
    leak_count = 0
    for first in range(slots):
        excluded = torch.zeros_like(batch.valid)
        excluded[:, first] = occupied[:, first]
        deleted_mask, _, telemetry = replay_store_masks(
            batch, queries, config, scores, excluded
        )
        deleted_loss = per_query_loss(
            host, memory, batch, deleted_mask, batch_size=batch_size
        )
        singleton[:, first] = normalized_conditional_effect(
            deleted_loss, full_loss, empty_loss
        )
        fallback_count += telemetry["fallback_versions_after_deletion"]
        leak_count += telemetry["dependency_payload_leaks"]
    upper = torch.triu(
        torch.ones((slots, slots), dtype=torch.bool, device=occupied.device),
        diagonal=1,
    )
    pair_valid = (
        occupied.unsqueeze(2) & occupied.unsqueeze(1) & upper.unsqueeze(0)
    )
    for first in range(slots):
        for second in range(first + 1, slots):
            eligible = occupied[:, first] & occupied[:, second]
            if not bool(eligible.any()):
                continue
            excluded = torch.zeros_like(batch.valid)
            excluded[:, first] = eligible
            excluded[:, second] = eligible
            deleted_mask, _, telemetry = replay_store_masks(
                batch, queries, config, scores, excluded
            )
            deleted_loss = per_query_loss(
                host, memory, batch, deleted_mask, batch_size=batch_size
            )
            target = normalized_conditional_effect(
                deleted_loss, full_loss, empty_loss
            )
            pair[:, first, second] = target
            pair[:, second, first] = target
            fallback_count += telemetry["fallback_versions_after_deletion"]
            leak_count += telemetry["dependency_payload_leaks"]
    singleton = singleton.masked_fill(~occupied, 0.0)
    telemetry = {
        **full_telemetry,
        "candidate_groups": int(occupied.sum()),
        "candidate_pairs": int(pair_valid.sum()),
        "full_store_retrieval_rate": float(full_mask.any(1).float().mean()),
        "fallback_versions_across_deletions": int(fallback_count),
        "dependency_payload_leaks_across_deletions": int(leak_count),
        "target": (
            "[L(reroute(rebuild(M without G)))-L(route(M))]/"
            "[L(empty)+1e-8]"
        ),
        "pair_deletions_included": True,
    }
    return ConditionalTargets(
        singleton=singleton,
        pair=pair,
        candidate=occupied,
        pair_valid=pair_valid,
        full_mask=full_mask,
        full_loss=full_loss,
        empty_loss=empty_loss,
        telemetry=telemetry,
    )


@dataclass
class CEFeatures:
    item: torch.Tensor
    candidate: torch.Tensor

    def index(self, index: torch.Tensor) -> "CEFeatures":
        return CEFeatures(item=self.item[index], candidate=self.candidate[index])


@torch.no_grad()
def build_ce_features(
    memory: RawMemoryConditioner,
    batch: QueryTensors,
    candidate: torch.Tensor,
) -> CEFeatures:
    query = memory.query_vector(
        batch.context_z, batch.future_actions[:, 0]
    )
    scores = store_scores(memory, batch)
    count = candidate.sum(1, keepdim=True).clamp_min(1)
    store_mean = (
        batch.events * candidate.unsqueeze(-1)
    ).sum(1) / count
    query_expand = query[:, None].expand(-1, batch.events.shape[1], -1)
    mean_expand = store_mean[:, None].expand_as(batch.events)
    occupancy = (
        candidate.sum(1, keepdim=True).float() / batch.events.shape[1]
    )[:, None].expand(-1, batch.events.shape[1], -1)
    centered_route = scores.route - (
        scores.route.masked_fill(~batch.valid, 0.0).sum(1, keepdim=True)
        / batch.valid.sum(1, keepdim=True).clamp_min(1)
    )
    item = torch.cat(
        [
            batch.events,
            query_expand,
            mean_expand,
            batch.events - mean_expand,
            batch.metadata,
            scores.ce_hat.unsqueeze(-1),
            centered_route.unsqueeze(-1),
            occupancy,
        ],
        dim=-1,
    ).detach()
    return CEFeatures(item=item, candidate=candidate)


class ConditionalCEHead(nn.Module):
    """Heteroscedastic item and symmetric pair conditional-effect predictor."""

    def __init__(self, input_dim: int, hidden: int = 192) -> None:
        super().__init__()
        self.encoder = nn.Sequential(
            nn.LayerNorm(input_dim),
            nn.Linear(input_dim, hidden),
            nn.GELU(),
            nn.Linear(hidden, hidden),
            nn.GELU(),
        )
        self.item_output = nn.Linear(hidden, 2)
        self.pair_output = nn.Sequential(
            nn.LayerNorm(3 * hidden),
            nn.Linear(3 * hidden, hidden),
            nn.GELU(),
            nn.Linear(hidden, 2),
        )

    def forward(
        self, item: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        hidden = self.encoder(item)
        output = self.item_output(hidden)
        return output[..., 0], output[..., 1].clamp(-8.0, 3.0), hidden

    def pair(
        self, hidden: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        left = hidden.unsqueeze(2)
        right = hidden.unsqueeze(1)
        symmetric = torch.cat(
            [left + right, (left - right).abs(), left * right], dim=-1
        )
        output = self.pair_output(symmetric)
        return output[..., 0], output[..., 1].clamp(-8.0, 3.0)


def heteroscedastic_loss(
    mean: torch.Tensor,
    log_variance: torch.Tensor,
    target: torch.Tensor,
) -> torch.Tensor:
    squared = torch.square(mean - target)
    return 0.5 * (torch.exp(-log_variance) * squared + log_variance)


def within_query_losses(
    prediction: torch.Tensor,
    target: torch.Tensor,
    valid: torch.Tensor,
    temperature: float,
) -> tuple[torch.Tensor, torch.Tensor]:
    true_delta = target.unsqueeze(2) - target.unsqueeze(1)
    pred_delta = prediction.unsqueeze(2) - prediction.unsqueeze(1)
    slots = prediction.shape[1]
    upper = torch.triu(
        torch.ones((slots, slots), dtype=torch.bool, device=prediction.device),
        diagonal=1,
    )
    pair_mask = (
        valid.unsqueeze(2)
        & valid.unsqueeze(1)
        & upper.unsqueeze(0)
        & (true_delta.abs() > 1e-6)
    )
    ranking = (
        F.softplus(
            -true_delta.sign() * pred_delta / max(temperature, 1e-4)
        )[pair_mask].mean()
        if bool(pair_mask.any())
        else prediction.new_zeros(())
    )
    eligible = valid.sum(1) >= 2
    if bool(eligible.any()):
        logits = (prediction / max(temperature, 1e-4)).masked_fill(
            ~valid, -1e9
        )
        truth = (target / max(temperature, 1e-4)).masked_fill(~valid, -1e9)
        target_probability = torch.softmax(truth[eligible], dim=1).detach()
        listwise = -(
            target_probability * torch.log_softmax(logits[eligible], dim=1)
        ).sum(1).mean()
    else:
        listwise = prediction.new_zeros(())
    return ranking, listwise


def train_conditional_head(
    head: ConditionalCEHead,
    train_features: CEFeatures,
    train_targets: ConditionalTargets,
    validation_features: CEFeatures,
    validation_targets: ConditionalTargets,
    args: argparse.Namespace,
) -> dict[str, Any]:
    optimizer = torch.optim.AdamW(
        head.parameters(), lr=args.conditional_lr, weight_decay=1e-4
    )
    rng = np.random.default_rng(args.seed + 31_337)
    target_values = train_targets.singleton[train_targets.candidate]
    temperature = max(
        1e-3, float(target_values.detach().float().std().cpu())
    )
    best_objective = float("inf")
    best_state = None
    best_epoch = 0
    stale = 0
    history = []
    for epoch in range(args.conditional_epochs):
        head.train()
        losses = []
        for indices in batches(len(train_features.item), args.batch_size, rng):
            index = torch.as_tensor(
                indices, device=train_features.item.device
            )
            features = train_features.index(index)
            truth = train_targets.singleton[index]
            pair_truth = train_targets.pair[index]
            pair_valid = train_targets.pair_valid[index]
            mean, log_variance, hidden = head(features.item)
            valid = features.candidate
            regression = heteroscedastic_loss(
                mean[valid], log_variance[valid], truth[valid]
            ).mean()
            calibration = F.smooth_l1_loss(
                mean[valid], truth[valid], beta=max(temperature, 1e-3)
            )
            ranking, listwise = within_query_losses(
                mean, truth, valid, temperature
            )
            pair_mean, pair_log_variance = head.pair(hidden)
            pair_regression = (
                heteroscedastic_loss(
                    pair_mean[pair_valid],
                    pair_log_variance[pair_valid],
                    pair_truth[pair_valid],
                ).mean()
                if bool(pair_valid.any())
                else regression.new_zeros(())
            )
            loss = (
                regression
                + 0.25 * calibration
                + ranking
                + 0.25 * listwise
                + 0.5 * pair_regression
            )
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(head.parameters(), 1.0)
            optimizer.step()
            losses.append(float(loss.detach()))
        head.eval()
        with torch.no_grad():
            val_mean, val_log_variance, val_hidden = head(
                validation_features.item
            )
            valid = validation_features.candidate
            val_nll = heteroscedastic_loss(
                val_mean[valid],
                val_log_variance[valid],
                validation_targets.singleton[valid],
            ).mean()
            val_rank, val_listwise = within_query_losses(
                val_mean,
                validation_targets.singleton,
                valid,
                temperature,
            )
            pair_mean, pair_log_variance = head.pair(val_hidden)
            pair_valid = validation_targets.pair_valid
            pair_nll = (
                heteroscedastic_loss(
                    pair_mean[pair_valid],
                    pair_log_variance[pair_valid],
                    validation_targets.pair[pair_valid],
                ).mean()
                if bool(pair_valid.any())
                else val_nll.new_zeros(())
            )
            objective = float(
                val_nll + val_rank + 0.25 * val_listwise + 0.5 * pair_nll
            )
        history.append(
            {
                "epoch": epoch + 1,
                "train_objective": float(np.mean(losses)),
                "validation_objective": objective,
                "validation_nll": float(val_nll),
                "validation_pair_nll": float(pair_nll),
            }
        )
        if math.isfinite(objective) and objective < best_objective - 1e-6:
            best_objective = objective
            best_epoch = epoch + 1
            best_state = {
                key: value.detach().cpu().clone()
                for key, value in head.state_dict().items()
            }
            stale = 0
        else:
            stale += 1
        if stale >= args.conditional_patience:
            break
    if best_state is None:
        raise RuntimeError("conditional head produced no finite checkpoint")
    head.load_state_dict(best_state)
    head.eval()
    return {
        "history": history,
        "best_epoch": best_epoch,
        "best_validation_objective": best_objective,
        "target_temperature": temperature,
        "heteroscedastic_regression": "Gaussian NLL plus Smooth-L1",
        "ranking": (
            "pairwise logistic and listwise softmax only within groups "
            "sharing the same occupied store/query"
        ),
        "pair_deletion_supervision": bool(train_targets.pair_valid.any()),
    }


def centered_rank_correlation(
    prediction: np.ndarray,
    target: np.ndarray,
    valid: np.ndarray,
) -> float | None:
    prediction_rows = []
    target_rows = []
    for row in range(len(prediction)):
        mask = valid[row]
        if int(mask.sum()) < 2:
            continue
        pred = prediction[row, mask]
        truth = target[row, mask]
        prediction_rows.append(pred - pred.mean())
        target_rows.append(truth - truth.mean())
    if not prediction_rows:
        return None
    return rank_correlation(
        np.concatenate(prediction_rows), np.concatenate(target_rows)
    )


def pairwise_query_statistics(
    prediction: np.ndarray,
    target: np.ndarray,
    valid: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    correct = np.zeros(len(prediction), dtype=np.float64)
    count = np.zeros(len(prediction), dtype=np.float64)
    for row in range(len(prediction)):
        indices = np.flatnonzero(valid[row])
        for offset, first in enumerate(indices):
            for second in indices[offset + 1 :]:
                true_delta = target[row, first] - target[row, second]
                if abs(float(true_delta)) <= 1e-6:
                    continue
                pred_delta = prediction[row, first] - prediction[row, second]
                correct[row] += float(pred_delta * true_delta > 0)
                count[row] += 1.0
    return correct, count


def deletion_gap_by_query(
    prediction: np.ndarray,
    target: np.ndarray,
    valid: np.ndarray,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    high = np.full(len(prediction), np.nan, dtype=np.float64)
    random_value = np.full(len(prediction), np.nan, dtype=np.float64)
    gap = np.full(len(prediction), np.nan, dtype=np.float64)
    rng = np.random.default_rng(seed)
    for row in range(len(prediction)):
        candidates = np.flatnonzero(valid[row])
        if len(candidates) < 2:
            continue
        high_slot = int(candidates[np.argmax(prediction[row, candidates])])
        random_slot = int(rng.choice(candidates))
        high[row] = target[row, high_slot]
        random_value[row] = target[row, random_slot]
        gap[row] = high[row] - random_value[row]
    return high, random_value, gap


def percentile_ci(
    values: np.ndarray,
    seed: int,
    repetitions: int = 2000,
) -> list[float | None]:
    finite = values[np.isfinite(values)]
    if not len(finite):
        return [None, None]
    if len(finite) == 1:
        return [float(finite[0]), float(finite[0])]
    rng = np.random.default_rng(seed)
    means = np.asarray(
        [
            rng.choice(finite, size=len(finite), replace=True).mean()
            for _ in range(repetitions)
        ]
    )
    return np.quantile(means, [0.025, 0.975]).astype(float).tolist()


def evaluate_predictions(
    prediction: np.ndarray,
    target: np.ndarray,
    valid: np.ndarray,
    seed: int,
) -> tuple[dict[str, Any], dict[str, np.ndarray]]:
    pooled = rank_correlation(prediction[valid], target[valid])
    centered = centered_rank_correlation(prediction, target, valid)
    correct, pair_count = pairwise_query_statistics(
        prediction, target, valid
    )
    high, random_value, gap = deletion_gap_by_query(
        prediction, target, valid, seed
    )
    total_pairs = float(pair_count.sum())
    finite_gap = gap[np.isfinite(gap)]
    metrics = {
        "pooled_spearman": pooled,
        "within_query_centered_spearman": centered,
        "pairwise_accuracy": (
            float(correct.sum() / total_pairs) if total_pairs else None
        ),
        "pair_count": int(total_pairs),
        "eligible_deletion_queries": int(len(finite_gap)),
        "high_conditional_effect": (
            float(np.nanmean(high)) if len(finite_gap) else None
        ),
        "random_conditional_effect": (
            float(np.nanmean(random_value)) if len(finite_gap) else None
        ),
        "high_minus_random": (
            float(np.nanmean(gap)) if len(finite_gap) else None
        ),
        "high_minus_random_query_bootstrap_ci95": percentile_ci(
            gap, seed + 81_119
        ),
    }
    arrays = {
        "prediction": prediction.astype(np.float32),
        "target": target.astype(np.float32),
        "valid": valid.astype(bool),
        "pair_correct": correct.astype(np.float32),
        "pair_count": pair_count.astype(np.float32),
        "high_effect": high.astype(np.float32),
        "random_effect": random_value.astype(np.float32),
        "deletion_gap": gap.astype(np.float32),
    }
    return metrics, arrays


def default_base_args(args: argparse.Namespace) -> argparse.Namespace:
    return argparse.Namespace(
        seed=args.seed,
        context=2,
        horizon=4,
        host_hidden=256,
        host_epochs=50,
        host_patience=8,
        host_lr=3e-4,
        memory_hidden=192,
        memory_epochs=35,
        memory_patience=7,
        memory_lr=4e-4,
        ce_epochs=25,
        ce_lr=5e-4,
        batch_size=args.batch_size,
        max_events=args.max_events,
        event_quantile=0.78,
        residual_cost=1e-3,
        smoke=args.smoke,
    )


def load_feature_arrays(
    base_output: Path,
    env_name: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    path = feature_path(base_output, env_name)
    if not path.is_file():
        raise FileNotFoundError(path)
    with np.load(path, allow_pickle=False) as data:
        return (
            np.asarray(data["latents"], dtype=np.float32),
            np.asarray(data["actions"], dtype=np.float32),
            np.asarray(data["train_indices"], dtype=np.int64),
            np.asarray(data["val_indices"], dtype=np.int64),
            np.asarray(data["test_indices"], dtype=np.int64),
        )


def prepare_base_model(
    args: argparse.Namespace,
    device: torch.device,
    output_dir: Path,
) -> tuple[
    ActionConditionedHost,
    RawMemoryConditioner,
    StoreConfig,
    dict[str, QueryTensors],
    dict[str, list[QuerySample]],
    dict[str, Any],
]:
    latents, actions, train_idx, val_idx, test_idx = load_feature_arrays(
        args.base_output, args.env_name
    )
    base_args = default_base_args(args)
    checkpoint_path = base_checkpoint_path(
        args.base_output, args.env_name, args.seed
    )
    trained_for_diagnostic = False
    if checkpoint_path.is_file():
        checkpoint = torch.load(
            checkpoint_path, map_location=device, weights_only=True
        )
        host_config = checkpoint["host_config"]
        host = ActionConditionedHost(
            host_config["latent_dim"],
            host_config["action_dim"],
            host_config["context"],
            host_config["hidden"],
        ).to(device)
        host.load_state_dict(checkpoint["host"])
        memory_config = checkpoint["memory_config"]
        memory = RawMemoryConditioner(
            host_config["latent_dim"],
            host_config["action_dim"],
            memory_config["hidden"],
            memory_config["budget"],
        ).to(device)
        memory.load_state_dict(checkpoint["memory"])
        config = StoreConfig(**checkpoint["store_config"])
        host_training = {"source": "checked-in raw CEM checkpoint"}
        memory_training = {"source": "checked-in raw CEM checkpoint"}
        ce_training = {"source": "checked-in raw CEM checkpoint"}
    else:
        trained_for_diagnostic = True
        host, host_training = train_host(
            latents, actions, train_idx, val_idx, base_args, device
        )
        memory = None
        config = None
        ce_training = None
        memory_training = None
    host.eval()
    for parameter in host.parameters():
        parameter.requires_grad_(False)
    host_digest_before = tensor_digest(host)
    surprise = one_step_surprise(
        host,
        latents,
        actions,
        device,
        base_args.context,
        base_args.batch_size,
    )
    events, discovery = discover_events(
        latents,
        surprise,
        train_idx,
        base_args.event_quantile,
    )
    semantic_keys = assign_semantic_keys(events, train_idx, args.seed)
    query_sets = {
        "train": build_queries(
            latents,
            actions,
            events,
            train_idx,
            base_args.context,
            base_args.horizon,
        ),
        "validation": build_queries(
            latents,
            actions,
            events,
            val_idx,
            base_args.context,
            base_args.horizon,
        ),
        "test": build_queries(
            latents,
            actions,
            events,
            test_idx,
            base_args.context,
            base_args.horizon,
        ),
    }
    if args.smoke:
        for split in query_sets:
            query_sets[split] = query_sets[split][
                : min(len(query_sets[split]), args.smoke_queries)
            ]
    tensors = {
        split: tensorize_queries(queries, device, args.max_events)
        for split, queries in query_sets.items()
    }
    if trained_for_diagnostic:
        memory, memory_training = train_memory(
            host,
            tensors["train"],
            tensors["validation"],
            base_args,
            device,
        )
        train_singleton, _, _ = compute_group_ce_targets(
            host, memory, tensors["train"], base_args.batch_size
        )
        validation_singleton, _, _ = compute_group_ce_targets(
            host, memory, tensors["validation"], base_args.batch_size
        )
        ce_training = train_ce_calibrator(
            memory,
            tensors["train"],
            train_singleton,
            tensors["validation"],
            validation_singleton,
            base_args,
        )
        config, _ = tune_store_config(
            host,
            memory,
            tensors["validation"],
            query_sets["validation"],
            base_args,
        )
        torch.save(
            {
                "schema": "cem_conditional_diagnostic_base_checkpoint",
                "host": host.state_dict(),
                "memory": memory.state_dict(),
                "host_config": {
                    "latent_dim": int(latents.shape[-1]),
                    "action_dim": int(actions.shape[-1]),
                    "context": base_args.context,
                    "hidden": base_args.host_hidden,
                },
                "memory_config": {
                    "hidden": base_args.memory_hidden,
                    "budget": base_args.max_events,
                },
                "store_config": asdict(config),
            },
            output_dir / "base_model.pt",
        )
        checkpoint_path = output_dir / "base_model.pt"
    assert memory is not None and config is not None
    memory.eval()
    for parameter in memory.parameters():
        parameter.requires_grad_(False)
    if tensor_digest(host) != host_digest_before:
        raise RuntimeError("frozen host changed during diagnostic preparation")
    provenance = {
        "base_checkpoint": str(checkpoint_path.relative_to(ROOT)),
        "base_checkpoint_sha256": sha256_file(checkpoint_path),
        "trained_missing_base_for_diagnostic": trained_for_diagnostic,
        "host_training": host_training,
        "memory_training": memory_training,
        "singleton_ce_training": ce_training,
        "base_store_config": asdict(config),
        "discovery": discovery,
        "semantic_keys": semantic_keys,
        "query_counts": {
            split: len(queries) for split, queries in query_sets.items()
        },
        "test_episode_ids": np.asarray(
            [query.episode_id for query in query_sets["test"]],
            dtype=np.int64,
        ),
    }
    return host, memory, config, tensors, query_sets, provenance


def run_cell(args: argparse.Namespace) -> dict[str, Any]:
    output_dir = cell_dir(args.output, args.env_name, args.seed)
    result_path = output_dir / "result.json"
    if result_path.is_file() and not args.overwrite:
        return json.loads(result_path.read_text())
    output_dir.mkdir(parents=True, exist_ok=True)
    started = time.time()
    set_seed(args.seed)
    device = resolve_device(args.gpu)
    (
        host,
        memory,
        base_config,
        tensors,
        query_sets,
        provenance,
    ) = prepare_base_model(args, device, output_dir)
    config = diagnostic_config(base_config, args.max_events)
    targets = {}
    features = {}
    for split in ("train", "validation", "test"):
        targets[split] = compute_conditional_targets(
            host,
            memory,
            tensors[split],
            query_sets[split],
            config,
            args.batch_size,
        )
        features[split] = build_ce_features(
            memory, tensors[split], targets[split].candidate
        )
    head = ConditionalCEHead(
        features["train"].item.shape[-1],
        hidden=args.conditional_hidden,
    ).to(device)
    training = train_conditional_head(
        head,
        features["train"],
        targets["train"],
        features["validation"],
        targets["validation"],
        args,
    )
    with torch.no_grad():
        conditional_prediction, log_variance, hidden = head(
            features["test"].item
        )
        pair_prediction, _ = head.pair(hidden)
        singleton_prediction = memory.query_ce_hat(
            tensors["test"].context_z,
            tensors["test"].future_actions[:, 0],
            tensors["test"].events,
            tensors["test"].metadata,
        )
        singleton_target, _, _ = compute_group_ce_targets(
            host, memory, tensors["test"], args.batch_size
        )
    candidate = targets["test"].candidate.detach().cpu().numpy()
    conditional_truth = targets["test"].singleton.detach().cpu().numpy()
    conditional_np = conditional_prediction.detach().cpu().numpy()
    singleton_np = singleton_prediction.detach().cpu().numpy()
    singleton_truth_np = singleton_target.detach().cpu().numpy()
    conditional_metrics, conditional_arrays = evaluate_predictions(
        conditional_np,
        conditional_truth,
        candidate,
        args.seed + 100_003,
    )
    singleton_conditional_metrics, singleton_arrays = evaluate_predictions(
        singleton_np,
        conditional_truth,
        candidate,
        args.seed + 200_003,
    )
    singleton_native_metrics, _ = evaluate_predictions(
        singleton_np,
        singleton_truth_np,
        tensors["test"].valid.detach().cpu().numpy(),
        args.seed + 300_007,
    )
    pair_valid = targets["test"].pair_valid
    pair_mae = (
        float(
            (
                pair_prediction[pair_valid]
                - targets["test"].pair[pair_valid]
            )
            .abs()
            .mean()
        )
        if bool(pair_valid.any())
        else None
    )
    pair_truth = targets["test"].pair.detach().cpu().numpy()
    singleton_sum = (
        conditional_truth[:, :, None] + conditional_truth[:, None, :]
    )
    interaction = pair_truth - singleton_sum
    pair_valid_np = pair_valid.detach().cpu().numpy()
    interaction_values = interaction[pair_valid_np]
    redundancy_fraction = (
        float(
            np.mean(
                (pair_truth[pair_valid_np] > 1e-6)
                & (
                    singleton_sum[pair_valid_np]
                    < 0.5 * pair_truth[pair_valid_np]
                )
            )
        )
        if len(interaction_values)
        else None
    )
    complement_fraction = (
        float(
            np.mean(
                interaction_values
                > np.maximum(
                    1e-6,
                    0.25 * np.abs(singleton_sum[pair_valid_np]),
                )
            )
        )
        if len(interaction_values)
        else None
    )
    episode_ids = provenance.pop("test_episode_ids")
    samples_path = output_dir / "evaluation.npz"
    np.savez_compressed(
        samples_path,
        episode_ids=episode_ids,
        candidate=candidate,
        conditional_target=conditional_truth,
        conditional_prediction=conditional_np,
        conditional_log_variance=log_variance.detach().cpu().numpy(),
        singleton_prediction=singleton_np,
        singleton_target=singleton_truth_np,
        conditional_pair_target=pair_truth,
        conditional_pair_prediction=pair_prediction.detach().cpu().numpy(),
        conditional_pair_valid=pair_valid_np,
        conditional_pair_correct=conditional_arrays["pair_correct"],
        conditional_pair_count=conditional_arrays["pair_count"],
        conditional_deletion_gap=conditional_arrays["deletion_gap"],
        singleton_pair_correct=singleton_arrays["pair_correct"],
        singleton_pair_count=singleton_arrays["pair_count"],
        singleton_deletion_gap=singleton_arrays["deletion_gap"],
    )
    checkpoint_path = output_dir / "conditional_head.pt"
    torch.save(
        {
            "schema": "cem_conditional_ce_head_v1",
            "head": head.state_dict(),
            "input_dim": int(features["train"].item.shape[-1]),
            "hidden": args.conditional_hidden,
            "diagnostic_store_config": asdict(config),
        },
        checkpoint_path,
    )
    audit = conditional_source_audit()
    if not audit["passed"]:
        raise RuntimeError(f"conditional no-label audit failed: {audit}")
    result = {
        "schema": "graph_cem_conditional_cell_v1",
        "status": "completed",
        "environment": args.env_name,
        "family": env_family(args.env_name),
        "seed": args.seed,
        "seed_role": (
            "host/memory optimization seed and conditional-head optimization "
            "seed; fixed recorded trajectory split"
        ),
        "device": str(device),
        "protocol": (
            "non-default flat conditional-target diagnostic over the existing "
            "raw OGBench DINO-feature CEM host"
        ),
        "source_contract": audit,
        "base": provenance,
        "diagnostic_store_config": asdict(config),
        "diagnostic_override": (
            "promotion threshold, hysteresis, verification delay, learned "
            "router, and version semantics are unchanged; capacity is at "
            "least four and read top-k is two to expose occupied-store "
            "interactions"
        ),
        "conditional_training": training,
        "target_telemetry": {
            split: targets[split].telemetry for split in targets
        },
        "test": {
            "conditional_ce_on_conditional_target": conditional_metrics,
            "singleton_ce_on_conditional_target": (
                singleton_conditional_metrics
            ),
            "singleton_ce_on_native_singleton_target": (
                singleton_native_metrics
            ),
            "pair_deletion": {
                "pair_count": int(pair_valid.sum()),
                "prediction_mae": pair_mae,
                "interaction_mean": (
                    float(np.mean(interaction_values))
                    if len(interaction_values)
                    else None
                ),
                "redundancy_signature_fraction": redundancy_fraction,
                "complementarity_signature_fraction": complement_fraction,
            },
        },
        "host_frozen_digest": tensor_digest(host),
        "artifacts": {
            "result": str(result_path.relative_to(ROOT)),
            "evaluation": str(samples_path.relative_to(ROOT)),
            "conditional_head": str(checkpoint_path.relative_to(ROOT)),
        },
        "elapsed_seconds": float(time.time() - started),
    }
    result_path.write_text(stable_json(json_safe(result)))
    print(
        stable_json(
            json_safe(
                {
                    "status": "completed",
                    "environment": args.env_name,
                    "seed": args.seed,
                    "conditional_spearman": conditional_metrics[
                        "within_query_centered_spearman"
                    ],
                    "conditional_pairwise": conditional_metrics[
                        "pairwise_accuracy"
                    ],
                    "conditional_deletion_gap": conditional_metrics[
                        "high_minus_random"
                    ],
                    "result": str(result_path.relative_to(ROOT)),
                }
            )
        ),
        flush=True,
    )
    return result


def sample_episode_indices(
    episode_ids: np.ndarray,
    rng: np.random.Generator,
) -> np.ndarray:
    unique = np.unique(episode_ids)
    sampled = rng.choice(unique, size=len(unique), replace=True)
    chunks = [np.flatnonzero(episode_ids == episode) for episode in sampled]
    return np.concatenate(chunks) if chunks else np.asarray([], dtype=np.int64)


def metric_from_sample(
    arrays: dict[str, np.ndarray],
    method: str,
    metric: str,
    index: np.ndarray,
) -> float:
    if metric == "spearman":
        prediction = arrays[
            "conditional_prediction"
            if method == "conditional"
            else "singleton_prediction"
        ][index]
        target = arrays["conditional_target"][index]
        valid = arrays["candidate"][index]
        value = centered_rank_correlation(prediction, target, valid)
        return float(value) if value is not None else float("nan")
    if metric == "pairwise":
        correct = arrays[f"{method}_pair_correct"][index].sum()
        count = arrays[f"{method}_pair_count"][index].sum()
        return float(correct / count) if count else float("nan")
    if metric == "deletion_gap":
        values = arrays[f"{method}_deletion_gap"][index]
        return (
            float(np.nanmean(values))
            if np.isfinite(values).any()
            else float("nan")
        )
    raise KeyError(metric)


def bootstrap_environment(
    cells: list[dict[str, Any]],
    method: str,
    metric: str,
    seed: int,
    repetitions: int,
) -> dict[str, Any]:
    loaded = []
    for cell in cells:
        path = ROOT / cell["artifacts"]["evaluation"]
        with np.load(path, allow_pickle=False) as data:
            loaded.append({key: np.asarray(data[key]) for key in data.files})
    point_values = []
    for arrays in loaded:
        index = np.arange(len(arrays["episode_ids"]))
        point_values.append(metric_from_sample(arrays, method, metric, index))
    point = float(np.nanmean(point_values))
    rng = np.random.default_rng(seed)
    draws = []
    for _ in range(repetitions):
        seed_indices = rng.choice(
            len(loaded), size=len(loaded), replace=True
        )
        values = []
        for seed_index in seed_indices:
            arrays = loaded[int(seed_index)]
            index = sample_episode_indices(arrays["episode_ids"], rng)
            values.append(metric_from_sample(arrays, method, metric, index))
        draws.append(float(np.nanmean(values)))
    draws_np = np.asarray(draws, dtype=np.float64)
    draws_np = draws_np[np.isfinite(draws_np)]
    return {
        "mean": point,
        "ci95": (
            np.quantile(draws_np, [0.025, 0.975]).astype(float).tolist()
            if len(draws_np)
            else [None, None]
        ),
        "seed_values": [float(value) for value in point_values],
        "seed_count": len(loaded),
        "bootstrap_unit": "optimization seed, then trajectory within seed",
        "_draws": draws_np,
    }


def aggregate(args: argparse.Namespace) -> dict[str, Any]:
    cells = []
    for path in sorted((args.output / "cells").glob("*/*/result.json")):
        result = json.loads(path.read_text())
        if result.get("schema") == "graph_cem_conditional_cell_v1":
            cells.append(result)
    grouped: dict[str, list[dict[str, Any]]] = {}
    for cell in cells:
        grouped.setdefault(cell["environment"], []).append(cell)
    environments = []
    global_draws: dict[tuple[str, str], list[np.ndarray]] = {}
    for env_index, (environment, rows) in enumerate(sorted(grouped.items())):
        methods = {}
        for method in ("conditional", "singleton"):
            methods[method] = {}
            for metric_index, metric in enumerate(
                ("spearman", "pairwise", "deletion_gap")
            ):
                summary = bootstrap_environment(
                    rows,
                    method,
                    metric,
                    seed=71_000 + env_index * 101 + metric_index * 17,
                    repetitions=args.bootstrap_repetitions,
                )
                global_draws.setdefault((method, metric), []).append(
                    summary.pop("_draws")
                )
                methods[method][metric] = summary
        environments.append(
            {
                "environment": environment,
                "family": rows[0]["family"],
                "seeds": sorted(int(row["seed"]) for row in rows),
                "methods": methods,
                "conditional_candidate_groups": int(
                    sum(
                        row["target_telemetry"]["test"]["candidate_groups"]
                        for row in rows
                    )
                ),
                "conditional_candidate_pairs": int(
                    sum(
                        row["target_telemetry"]["test"]["candidate_pairs"]
                        for row in rows
                    )
                ),
                "dependency_payload_leaks": int(
                    sum(
                        row["target_telemetry"]["test"][
                            "dependency_payload_leaks_across_deletions"
                        ]
                        for row in rows
                    )
                ),
            }
        )
    aggregate_metrics = {}
    for method in ("conditional", "singleton"):
        aggregate_metrics[method] = {}
        for metric in ("spearman", "pairwise", "deletion_gap"):
            env_summaries = [
                environment["methods"][method][metric]
                for environment in environments
            ]
            point = (
                float(np.mean([summary["mean"] for summary in env_summaries]))
                if env_summaries
                else None
            )
            draws_by_env = global_draws.get((method, metric), [])
            if draws_by_env:
                length = min(len(values) for values in draws_by_env)
                stacked = np.stack(
                    [values[:length] for values in draws_by_env]
                )
                global_values = stacked.mean(0)
                ci = np.quantile(
                    global_values, [0.025, 0.975]
                ).astype(float).tolist()
            else:
                ci = [None, None]
            aggregate_metrics[method][metric] = {
                "mean": point,
                "ci95": ci,
                "hierarchy": (
                    "environment mean of seed/trajectory nested bootstrap"
                ),
            }
    conditional = aggregate_metrics.get("conditional", {})
    spearman = conditional.get("spearman", {})
    pairwise = conditional.get("pairwise", {})
    positive_deletion_envs = [
        environment["environment"]
        for environment in environments
        if (
            environment["methods"]["conditional"]["deletion_gap"]["ci95"][0]
            is not None
            and environment["methods"]["conditional"]["deletion_gap"][
                "ci95"
            ][0]
            > 0
        )
    ]
    rank_pass = bool(
        (
            spearman.get("ci95", [None])[0] is not None
            and spearman["ci95"][0] > 0.2
        )
        or (
            pairwise.get("mean") is not None
            and pairwise["mean"] >= 0.65
        )
    )
    deletion_pass = len(positive_deletion_envs) >= 2
    gate = {
        "name": "Gate 1: flat conditional-target headroom",
        "passed": bool(rank_pass and deletion_pass),
        "rank_criterion": {
            "passed": rank_pass,
            "conditional_within_query_spearman": spearman,
            "conditional_pairwise_accuracy": pairwise,
            "rule": "Spearman lower CI > 0.2 OR pairwise accuracy >= 0.65",
        },
        "deletion_criterion": {
            "passed": deletion_pass,
            "positive_lower_ci_environments": positive_deletion_envs,
            "count": len(positive_deletion_envs),
            "rule": "conditional high-minus-random lower CI > 0 on >=2/3 envs",
        },
    }
    report = {
        "schema": "graph_cem_conditional_report_v1",
        "status": "completed" if cells else "empty",
        "phase": 1,
        "cell_count": len(cells),
        "environment_count": len(environments),
        "source_contract": conditional_source_audit(),
        "target_definition": (
            "D(G|M,q)=[L(rebuild_and_reroute(M without G),q)-L(M,q)]/"
            "[L(empty,q)+1e-8]"
        ),
        "environments": environments,
        "aggregate": aggregate_metrics,
        "gate": gate,
        "jobs_still_running": [],
        "artifacts": {
            "cells": (
                "outputs/graph_cem_conditional_v1/cells/<env>/s<seed>"
            ),
            "report": "outputs/graph_cem_conditional_v1/report.json",
        },
    }
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "report.json").write_text(
        stable_json(json_safe(report))
    )
    print(stable_json(json_safe(report)), flush=True)
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env-name")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--gpu", type=int, default=0)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--base-output", type=Path, default=DEFAULT_BASE_OUTPUT
    )
    parser.add_argument("--aggregate", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--smoke-queries", type=int, default=192)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--max-events", type=int, default=8)
    parser.add_argument("--conditional-hidden", type=int, default=192)
    parser.add_argument("--conditional-epochs", type=int, default=30)
    parser.add_argument("--conditional-patience", type=int, default=7)
    parser.add_argument("--conditional-lr", type=float, default=4e-4)
    parser.add_argument("--bootstrap-repetitions", type=int, default=2000)
    args = parser.parse_args()
    for name in ("output", "base_output"):
        value = getattr(args, name)
        if not value.is_absolute():
            setattr(args, name, ROOT / value)
    if args.gpu == 3 or args.gpu not in (0, 1, 2):
        parser.error("--gpu must be one of 0,1,2; GPU3 is prohibited")
    if args.smoke:
        args.conditional_epochs = min(args.conditional_epochs, 3)
        args.conditional_patience = min(args.conditional_patience, 2)
        args.bootstrap_repetitions = min(args.bootstrap_repetitions, 100)
    return args


def main() -> None:
    args = parse_args()
    if args.aggregate:
        aggregate(args)
        return
    if args.env_name not in FOCUSED_ENVS:
        raise ValueError(
            f"--env-name must be one of {FOCUSED_ENVS}; received {args.env_name}"
        )
    run_cell(args)


if __name__ == "__main__":
    main()
