"""Controlled PointMaze memory task and current-MuJoCo execution adapter.

The visual task is deliberately counterfactual: every native trajectory
window is repeated under four transient goal cards.  Images outside cue
frames, actions, proprioception, physics state, and the decision endpoint are
bit-identical across the four repetitions.  Only the location of a red goal
dot inside a fixed mini-map changes.

The released DINO-WM environment was written for ``mujoco_py``/D4RL.  For an
executed-use check on a maintained runtime, :class:`CurrentMujocoPointMaze`
loads the XML generated by the *unmodified released source* and advances it
with MuJoCo's current Python bindings.  It preserves the official 0.01 s
Euler step, five simulator steps per action, control clipping, velocity
clipping, actuator gears, and maze geometry.  No renderer is involved in the
execution score.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import importlib.util
import io
from pathlib import Path
import sys
import types
from typing import Any, Sequence

import numpy as np


U_MAZE = "#####\\#GOO#\\###O#\\#OOO#\\#####"
GOAL_WAYPOINTS = np.asarray(
    [[1.0, 1.0], [1.0, 3.0], [3.0, 1.0], [3.0, 3.0]],
    dtype=np.float64,
)
CUE_TOP = 8
CUE_LEFT = 8
CUE_SIZE = 72


@dataclass(frozen=True)
class MazeSelection:
    """One native, episode-disjoint trajectory window."""

    split: str
    episode_index: int
    local_start: int


def endpoint_frame(last_cue_frame: int, evidence_age: int) -> int:
    if isinstance(last_cue_frame, bool) or int(last_cue_frame) < 0:
        raise ValueError("last_cue_frame must be a non-negative integer")
    if isinstance(evidence_age, bool) or int(evidence_age) < 1:
        raise ValueError("evidence_age must be a positive integer")
    return int(last_cue_frame) + int(evidence_age)


def predictor_context_for_endpoint(endpoint: int) -> tuple[int, int, int]:
    if isinstance(endpoint, bool) or int(endpoint) < 3:
        raise ValueError("endpoint must be an integer >= 3")
    endpoint = int(endpoint)
    return endpoint - 3, endpoint - 2, endpoint - 1


def select_native_windows(
    sequence_lengths: Sequence[int], *, train_episodes: Sequence[int],
    validation_episodes: Sequence[int], train_count: int,
    validation_count: int, num_frames: int, frame_skip: int, seed: int,
) -> list[MazeSelection]:
    """Select windows without crossing the native episode split.

    The eligibility convention exactly follows DINO-WM's
    ``TrajSlicerDataset``: a length-``num_frames`` sequence at stride
    ``frame_skip`` also owns the complete final action block, hence
    ``start + num_frames * frame_skip <= episode_length``.
    """

    lengths = np.asarray(sequence_lengths, dtype=np.int64)
    if lengths.ndim != 1 or np.any(lengths < 1):
        raise ValueError("sequence_lengths must be a positive vector")
    if set(map(int, train_episodes)) & set(map(int, validation_episodes)):
        raise ValueError("native train and validation episodes overlap")
    if min(train_count, validation_count, num_frames, frame_skip) < 1:
        raise ValueError("counts, num_frames, and frame_skip must be positive")
    rng = np.random.default_rng(int(seed))

    def sample(episodes: Sequence[int], count: int, split: str) \
            -> list[MazeSelection]:
        eligible: list[tuple[int, int]] = []
        span = int(num_frames) * int(frame_skip)
        for raw_episode in episodes:
            episode = int(raw_episode)
            if episode < 0 or episode >= len(lengths):
                raise ValueError(f"episode index out of range: {episode}")
            eligible.extend((episode, start) for start in range(
                max(0, int(lengths[episode]) - span + 1)))
        if len(eligible) < count:
            raise ValueError(
                f"{split} has {len(eligible)} eligible windows, needs {count}")
        chosen = rng.choice(len(eligible), size=count, replace=False)
        return [MazeSelection(split, *eligible[int(index)]) for index in chosen]

    return sample(train_episodes, int(train_count), "train") + sample(
        validation_episodes, int(validation_count), "validation")


def _fill_rectangle(image: np.ndarray, top: int, left: int, bottom: int,
                    right: int, color: Sequence[int]) -> None:
    image[top:bottom, left:right] = np.asarray(color, dtype=np.uint8)


def _fill_circle(image: np.ndarray, center_y: int, center_x: int,
                 radius: int, color: Sequence[int]) -> None:
    yy, xx = np.ogrid[:image.shape[0], :image.shape[1]]
    mask = (yy - center_y) ** 2 + (xx - center_x) ** 2 <= radius ** 2
    image[mask] = np.asarray(color, dtype=np.uint8)


def goal_card(label: int) -> np.ndarray:
    """Return the fixed 72x72 mini-map card for one of four maze goals."""

    if isinstance(label, bool) or int(label) not in range(4):
        raise ValueError("goal label must be an integer in [0,3]")
    label = int(label)
    card = np.full((CUE_SIZE, CUE_SIZE, 3), 22, dtype=np.uint8)
    _fill_rectangle(card, 0, 0, CUE_SIZE, CUE_SIZE, (245, 245, 245))
    _fill_rectangle(card, 3, 3, CUE_SIZE - 3, CUE_SIZE - 3, (25, 29, 36))
    # A thick U-shaped route glyph.  All pixels except the red goal marker are
    # label-invariant, so class identity is encoded only by goal location.
    route = (164, 176, 190)
    _fill_rectangle(card, 15, 14, 56, 22, route)
    _fill_rectangle(card, 15, 50, 56, 58, route)
    _fill_rectangle(card, 48, 14, 56, 59, route)
    _fill_rectangle(card, 15, 21, 23, 51, route)
    centers = ((19, 18), (19, 54), (52, 18), (52, 54))
    _fill_circle(card, *centers[label], 8, (250, 64, 64))
    _fill_circle(card, *centers[label], 3, (255, 235, 235))
    return card


def render_transient_goal_cue(frames: np.ndarray, label: int, *,
                              cue_start: int = 1,
                              cue_length: int = 3) -> np.ndarray:
    """Overlay a cue card while leaving every non-cue pixel unchanged."""

    values = np.asarray(frames)
    if values.ndim != 4 or values.shape[1:] != (224, 224, 3) \
            or values.dtype != np.uint8:
        raise ValueError("frames must be uint8 (T,224,224,3)")
    if cue_start < 0 or cue_length < 1 or cue_start + cue_length > len(values):
        raise ValueError("cue interval lies outside frames")
    output = values.copy()
    card = goal_card(label)
    output[cue_start:cue_start + cue_length,
           CUE_TOP:CUE_TOP + CUE_SIZE,
           CUE_LEFT:CUE_LEFT + CUE_SIZE] = card
    return output


def verify_cue_only_counterfactual(base: np.ndarray,
                                   variants: np.ndarray, *,
                                   cue_start: int = 1,
                                   cue_length: int = 3) -> dict[str, Any]:
    """Audit that a four-label deck differs only in the declared cue patch."""

    base = np.asarray(base)
    variants = np.asarray(variants)
    if variants.shape != (4, *base.shape):
        raise ValueError("variants must have shape (4,*base.shape)")
    allowed = np.zeros(base.shape[:-1], dtype=np.bool_)
    allowed[cue_start:cue_start + cue_length,
            CUE_TOP:CUE_TOP + CUE_SIZE,
            CUE_LEFT:CUE_LEFT + CUE_SIZE] = True
    delta = np.any(variants != base[None], axis=-1)
    outside = np.logical_and(delta, ~allowed[None])
    pairwise_outside = 0
    for left in range(4):
        for right in range(left + 1, 4):
            mismatch = np.any(variants[left] != variants[right], axis=-1)
            pairwise_outside += int(np.count_nonzero(mismatch & ~allowed))
    cue_changes = [int(np.count_nonzero(delta[label] & allowed))
                   for label in range(4)]
    return {
        "outside_declared_mask_changed_pixels": int(np.count_nonzero(outside)),
        "pairwise_outside_mask_changed_pixels": pairwise_outside,
        "cue_changed_pixels_per_label": cue_changes,
        "all_labels_change_cue": bool(min(cue_changes) > 0),
        "passed": bool(not np.any(outside) and pairwise_outside == 0
                       and min(cue_changes) > 0),
    }


def _load_released_pointmaze_modules(vendor_root: Path) -> tuple[Any, Any]:
    """Load two released source files without executing their legacy package."""

    pointmaze = Path(vendor_root) / "env/pointmaze"
    if not pointmaze.is_dir():
        raise FileNotFoundError(f"released PointMaze source missing: {pointmaze}")
    digest = hashlib.sha256(str(pointmaze.resolve()).encode()).hexdigest()[:12]
    package_name = f"_lewm_released_pointmaze_{digest}"
    package = sys.modules.get(package_name)
    if package is None:
        package = types.ModuleType(package_name)
        package.__path__ = [str(pointmaze)]
        sys.modules[package_name] = package

    # maze_model imports D4RL only to define a legacy Gym wrapper.  XML
    # generation itself is independent.  A minimal local namespace lets us
    # execute the released function without installing obsolete D4RL.
    if "d4rl" not in sys.modules:
        d4rl = types.ModuleType("d4rl")
        offline = types.ModuleType("d4rl.offline_env")
        offline.OfflineEnv = type("OfflineEnv", (), {})
        d4rl.offline_env = offline
        sys.modules["d4rl"] = d4rl
        sys.modules["d4rl.offline_env"] = offline

    def load(name: str) -> Any:
        qualified = f"{package_name}.{name}"
        if qualified in sys.modules:
            return sys.modules[qualified]
        path = pointmaze / f"{name}.py"
        spec = importlib.util.spec_from_file_location(qualified, path)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot load released source {path}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[qualified] = module
        spec.loader.exec_module(module)
        return module

    load("dynamic_mjc")
    maze_model = load("maze_model")
    waypoint = load("waypoint_controller")
    return maze_model, waypoint


def released_pointmaze_xml(vendor_root: Path) -> str:
    maze_model, _ = _load_released_pointmaze_modules(vendor_root)
    model = maze_model.point_maze(maze_model.U_MAZE)
    stream = io.StringIO()
    model.root.write(stream)
    return stream.getvalue()


class CurrentMujocoPointMaze:
    """Current-MuJoCo execution of the released U-maze physics XML."""

    def __init__(self, vendor_root: Path) -> None:
        import mujoco

        self.mujoco = mujoco
        self.xml = released_pointmaze_xml(vendor_root)
        self.xml_sha256 = hashlib.sha256(self.xml.encode()).hexdigest()
        self.model = mujoco.MjModel.from_xml_string(self.xml)
        self.data = mujoco.MjData(self.model)
        if (self.model.nq, self.model.nv, self.model.nu) != (2, 2, 2):
            raise RuntimeError("released PointMaze model dimensions changed")
        if abs(float(self.model.opt.timestep) - 0.01) > 1e-15:
            raise RuntimeError("released PointMaze timestep changed")
        if not np.array_equal(self.model.actuator_ctrlrange,
                              np.asarray([[-1.0, 1.0], [-1.0, 1.0]])):
            raise RuntimeError("released PointMaze control bounds changed")
        if not np.array_equal(self.model.actuator_gear[:, :2],
                              np.asarray([[100.0, 0.0], [100.0, 0.0]])):
            raise RuntimeError("released PointMaze actuator gears changed")

    def reset(self, state: np.ndarray) -> np.ndarray:
        state = np.asarray(state, dtype=np.float64)
        if state.shape != (4,) or not np.isfinite(state).all():
            raise ValueError("PointMaze state must be finite [x,y,vx,vy]")
        self.mujoco.mj_resetData(self.model, self.data)
        self.data.qpos[:] = state[:2]
        self.data.qvel[:] = state[2:]
        self.mujoco.mj_forward(self.model, self.data)
        return self.state()

    def state(self) -> np.ndarray:
        return np.concatenate((self.data.qpos.copy(), self.data.qvel.copy()))

    def step(self, action: np.ndarray) -> np.ndarray:
        action = np.asarray(action, dtype=np.float64)
        if action.shape != (2,) or not np.isfinite(action).all():
            raise ValueError("PointMaze action must be a finite 2-vector")
        self.data.qvel[:] = np.clip(self.data.qvel, -5.0, 5.0)
        self.data.ctrl[:] = np.clip(action, -1.0, 1.0)
        for _ in range(5):
            self.mujoco.mj_step(self.model, self.data)
        return self.state()


def execute_released_waypoint(
    simulator: CurrentMujocoPointMaze, vendor_root: Path, *,
    initial_state: np.ndarray, target: np.ndarray, horizon: int,
    controller_seed: int, success_radius: float,
) -> dict[str, Any]:
    """Execute the released waypoint controller in current MuJoCo."""

    if horizon < 1 or success_radius <= 0:
        raise ValueError("horizon and success_radius must be positive")
    _, waypoint = _load_released_pointmaze_modules(vendor_root)
    # The released controller jitters intermediate waypoints via NumPy's
    # global RNG.  Isolating and restoring that state makes replay exact.
    random_state = np.random.get_state()
    try:
        np.random.seed(int(controller_seed))
        controller = waypoint.WaypointController(U_MAZE)
        reset_state = simulator.reset(np.asarray(initial_state, dtype=np.float64))
        trajectory = [reset_state.copy()]
        reached = False
        for _ in range(int(horizon)):
            state = simulator.state()
            action, controller_done = controller.get_action(
                state[:2].copy(), state[2:].copy(),
                np.asarray(target, dtype=np.float64))
            state = simulator.step(action)
            trajectory.append(state.copy())
            reached = bool(controller_done) or (
                np.linalg.norm(state[:2] - target) < 0.10
                and np.linalg.norm(state[2:]) < 0.10)
            if reached:
                break
    finally:
        np.random.set_state(random_state)
    final = simulator.state()
    return {
        "reset_state": reset_state,
        "final_state": final,
        "trajectory": np.stack(trajectory),
        "controller_reached": reached,
        "success": bool(np.linalg.norm(final[:2] - target) < success_radius),
        "steps": len(trajectory) - 1,
    }


def crossed_execution_arrays(success_matrix: np.ndarray,
                             predictions: np.ndarray,
                             truth: np.ndarray) -> dict[str, np.ndarray]:
    """Score selected goals against the *true* counterfactual goal."""

    matrix = np.asarray(success_matrix)
    prediction = np.asarray(predictions, dtype=np.int64)
    truth = np.asarray(truth, dtype=np.int64)
    if matrix.ndim != 3 or matrix.shape[1:] != (4, 4):
        raise ValueError("success_matrix must be (base,selected,true)")
    if prediction.shape != truth.shape or prediction.ndim != 1:
        raise ValueError("prediction and truth must be aligned vectors")
    # Expanded deck ordering is base-major, then label 0..3.
    base = np.arange(len(truth), dtype=np.int64) // 4
    if len(truth) != matrix.shape[0] * 4:
        raise ValueError("expanded truth length differs from success deck")
    rows = np.arange(len(truth))
    executed = matrix[base, prediction, truth].astype(np.int8)
    oracle = matrix[base, truth, truth].astype(np.int8)
    return {
        "goal_correct": (prediction == truth).astype(np.int8),
        "executed_success": executed,
        "oracle_success": oracle,
        "row": rows,
        "base": base,
    }


__all__ = [
    "U_MAZE", "GOAL_WAYPOINTS", "CUE_TOP", "CUE_LEFT", "CUE_SIZE",
    "MazeSelection", "endpoint_frame", "predictor_context_for_endpoint",
    "select_native_windows", "goal_card", "render_transient_goal_cue",
    "verify_cue_only_counterfactual", "released_pointmaze_xml",
    "CurrentMujocoPointMaze", "execute_released_waypoint",
    "crossed_execution_arrays",
]
